name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - test-ci**
  workflow_dispatch: # Enable workflow to be run manually

# Cancel the currently running CI job if you push a change while CI is running
# Documentation: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-22.04
    name: Run checks
    env:
      PYTHON_VERSION: 3.7.17
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements-lock.txt
      - name: Install dependencies into Python environment
        run: |
          make update

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: precommit--${{ runner.os }}--${{ runner.arch }}--${{ env.PYTHON_VERSION }}--${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run all checks
        run: |
          SKIP=actionlint,no-commit-to-branch make check
